services:
  - type: web
    name: saas-invoice-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: VERIFICATION_EXPIRATION
        value: "3600000"
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
